; Surcharge Vercel — si ce fichier remplace le php.ini runtime,
; il faut recharger les extensions nécessaires.
extension = mongodb
extension = pdo_mysql
extension = mysqli
extension = openssl
extension = mbstring
extension = curl

memory_limit = 256M
max_execution_time = 60
session.save_path = /tmp
